### ISSUE TITLE
Nix-shell install seems incomplete (error about no package.json)

### ISSUE THREAD

**Issue by fwip** [silviogutierrez/reactivated#251] opened 2023-04-30 19:28 UTC
Background:

I have Nix installed on Mac. I ran the instructions listed here: https://www.reactivated.io/documentation/getting-started/

The `nix-shell -E $(curl ...)` command possibly did not finish properly, as I was left in the nix-shell until exiting a few times (see log below).

Once exiting the nix-shell created by that command, attempting to run `nix-shell` in the new directory complains that no `package.json` file exists.

This log is from the second time I tried it, after removing the directory created the first time. (That is why there aren't a bunch of nix download commands in here, I think).

<details>

```
projects/futz/reactivated-test 
➜  nix-shell -E "$(curl -L https://reactivated.io/install/)"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   434  100   434    0     0    288      0  0:00:01  0:00:01 --:--:--     0
Enter a project name
rv-demo
Initialized empty Git repository in /Volumes/projects/futz/reactivated-test/rv-demo/.git/
bash-5.2$ ls
Dockerfile  client  manage.py  mypy.ini  pytest.ini  requirements.nix  requirements.txt  scripts  server  shell.nix  static  tsconfig.json
bash-5.2$ ls server/                                                                                                                                                                                       
__init__.py  asgi.py  example  settings  urls.py  wsgi.py
bash-5.2$ find . -name 'package.json'                                                                                                                                                                      
bash-5.2$ exit                                                                                                                                                                                             
bash-5.2$ exit
bash-5.2$ exit
bash-5.2$ exit
bash-5.2$ exit
[main (root-commit) 2e4a2c7] Initial files
 55 files changed, 2056 insertions(+)
 create mode 100644 .babelrc.json
 create mode 100644 .dockerignore
 create mode 100644 .editorconfig
 create mode 100644 .eslintrc.json
 create mode 100644 .flake8
 create mode 100644 .gitignore
 create mode 100644 .isort.cfg
 create mode 100644 .prettierrc
 create mode 100644 .shellcheckrc
 create mode 100644 Dockerfile
 create mode 100644 client/components/Layout.tsx
 create mode 100644 client/forms.tsx
 create mode 100644 client/index.tsx
 create mode 100644 client/styles.tsx
 create mode 100644 client/templates/DjangoDefault.tsx
 create mode 100644 client/templates/EditPoll.tsx
 create mode 100644 client/templates/FormPlayground.tsx
 create mode 100644 client/templates/PollComments.tsx
 create mode 100644 client/templates/PollDetail.tsx
 create mode 100644 client/templates/PollsIndex.tsx
 create mode 100644 client/templates/Results.tsx
 create mode 100755 manage.py
 create mode 100644 mypy.ini
 create mode 100644 pytest.ini
 create mode 100644 requirements.nix
 create mode 100644 requirements.txt
 create mode 100755 scripts/deploy.sh
 create mode 100755 scripts/fix.sh
 create mode 100644 scripts/helpers.sh
 create mode 100755 scripts/launch.sh
 create mode 100755 scripts/remove_example.sh
 create mode 100755 scripts/test.sh
 create mode 100644 server/__init__.py
 create mode 100644 server/asgi.py
 create mode 100644 server/example/__init__.py
 create mode 100644 server/example/admin.py
 create mode 100644 server/example/apps.py
 create mode 100644 server/example/context_processors.py
 create mode 100644 server/example/forms.py
 create mode 100644 server/example/migrations/0001_initial.py
 create mode 100644 server/example/migrations/__init__.py
 create mode 100644 server/example/models.py
 create mode 100644 server/example/templates.py
 create mode 100644 server/example/tests.py
 create mode 100644 server/example/urls.py
 create mode 100644 server/example/views.py
 create mode 120000 server/settings/__init__.py
 create mode 100644 server/settings/common.py
 create mode 100644 server/settings/localhost.py
 create mode 100644 server/settings/production.py
 create mode 100644 server/urls.py
 create mode 100644 server/wsgi.py
 create mode 100644 shell.nix
 create mode 100644 static/favicon.ico
 create mode 100644 tsconfig.json


All done. You can start your project by running

cd rv-demo
nix-shell
python manage.py runserver

projects/futz/reactivated-test took 1m5s 
➜  cd rv-demo 

rv-demo on  main via  v3.10.6 
➜  nix-shell
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Volumes/projects/futz/reactivated-test/rv-demo/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/projects/futz/reactivated-test/rv-demo/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nelsonjs/.npm/_logs/2023-04-30T19_17_30_168Z-debug-0.log
bash: /Volumes/projects/futz/reactivated-test/rv-demo/node_modules/.bin/setup_environment.sh: No such file or directory

[nix-shell:/Volumes/projects/futz/reactivated-test/rv-demo]$ python manage.py runserver
Traceback (most recent call last):
  File "/Volumes/projects/futz/reactivated-test/rv-demo/manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/projects/futz/reactivated-test/rv-demo/manage.py", line 22, in <module>
    main()
  File "/Volumes/projects/futz/reactivated-test/rv-demo/manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

[nix-shell:/Volumes/projects/futz/reactivated-test/rv-demo]$ 
```

</details>

**Comment by silviogutierrez** [comment] 2023-05-09 16:42
Hi @fwip , I still can't reproduce so I'll close this issue. But feel free to reopen if you have any more information to provide.

**Closed by silviogutierrez** 2023-05-09 16:42 UTC
